//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeeOtp2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeeOtp2.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clock {
            get {
                object obj = ResourceManager.GetObject("clock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (C) 2012-2013 Devin Martin
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a
        ///copy of this software and associated documentation files (the &quot;Software&quot;),
        ///to deal in the Software without restriction, including without limitation
        ///the rights to use, copy, modify, merge, publish, distribute, sublicense,
        ///and/or sell copies of the Software, and to permit persons to whom the
        ///Software is furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KeeOtpLICENSE {
            get {
                return ResourceManager.GetString("KeeOtpLICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lock_key {
            get {
                object obj = ResourceManager.GetObject("lock_key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (C) 2012 Devin Martin
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a
        ///copy of this software and associated documentation files (the &quot;Software&quot;),
        ///to deal in the Software without restriction, including without limitation
        ///the rights to use, copy, modify, merge, publish, distribute, sublicense,
        ///and/or sell copies of the Software, and to permit persons to whom the
        ///Software is furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OtpSharpLICENSE {
            get {
                return ResourceManager.GetString("OtpSharpLICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIT License (MIT)
        ///
        ///Copyright (c) 2013-2018 Raffael Herrmann
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of
        ///this software and associated documentation files (the &quot;Software&quot;), to deal in
        ///the Software without restriction, including without limitation the rights to
        ///use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
        ///the Software, and to permit persons to whom the Software is furnished to do so,
        ///subject to the following conditions:
        ///
        ///Th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QRCoderLICENSE {
            get {
                return ResourceManager.GetString("QRCoderLICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIT License (MIT)
        ///
        ///Copyright (c) 2015 Troy Willmot
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string YortNtpPortableLICENSE {
            get {
                return ResourceManager.GetString("YortNtpPortableLICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                  Apache License
        ///                           Version 2.0, January 2004
        ///                        http://www.apache.org/licenses/
        ///
        ///   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
        ///
        ///   1. Definitions.
        ///
        ///      &quot;License&quot; shall mean the terms and conditions for use, reproduction,
        ///      and distribution as defined by Sections 1 through 9 of this document.
        ///
        ///      &quot;Licensor&quot; shall mean the copyright owner or entity authorized by
        ///      the copyright owner that is [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ZXingNetLICENSE {
            get {
                return ResourceManager.GetString("ZXingNetLICENSE", resourceCulture);
            }
        }
    }
}
